# Generated by Django 6.1.1 on 2026-09-30 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('codigo', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('precio', models.PositiveIntegerField(help_text='Céntimos de sol')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('saldo', models.IntegerField(default=0, help_text='Céntimos de sol (saldo real)')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.tarifa')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('bloqueada', 'Bloqueada'), ('anulada', 'Anulada')], default='pendiente', max_length=10)),
                ('emitida', models.DateTimeField(auto_now_add=True)),
                ('bloqueada_en', models.DateTimeField(blank=True, null=True)),
                ('recarga_inicial', models.PositiveIntegerField(default=0)),
                ('creo_cuenta', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='transporte.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=20)),
                ('monto', models.IntegerField(help_text='Céntimos (negativo = cobro)')),
                ('saldo_final', models.IntegerField()),
                ('operacion', models.PositiveIntegerField(blank=True, help_text='N.º de operación grabado en la tarjeta', null=True)),
                ('validador', models.PositiveIntegerField(blank=True, null=True)),
                ('ref', models.CharField(blank=True, help_text='Id único del origen (p. ej. V101-57): evita duplicados', max_length=40, null=True, unique=True)),
                ('contador', models.PositiveIntegerField(blank=True, help_text='Contador NFC', null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='transporte.cuenta')),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transporte.tarjeta')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=60)),
                ('detalle', models.TextField(blank=True)),
                ('revisada', models.BooleanField(default=False)),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.tarjeta')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Validador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Id grabado en la tarjeta (1-899)', unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Bus, placa, ruta...', max_length=80)),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'validadores',
            },
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(help_text='Correlativo por cuenta: 1, 2, 3...')),
                ('monto', models.PositiveIntegerField(help_text='Céntimos de sol')),
                ('origen', models.CharField(max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('aplicada_en', models.DateTimeField(blank=True, help_text='Cuándo llegó a la tarjeta (vacío = pendiente)', null=True)),
                ('aplicada_por', models.PositiveIntegerField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recargas', to='transporte.cuenta')),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transporte.tarjeta')),
            ],
            options={
                'ordering': ['cuenta', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('cuenta', 'seq'), name='recarga_seq_unica')],
            },
        ),
    ]
